export const courses = [
  [
    "Elements of AI",
    "University of Helsinki / MinnaLearn",
    "Beginner",
    "AI Literacy",
    "Free",
    "A friendly introduction to what AI is, what it can do, and how it affects society.",
    "https://www.elementsofai.com/",
  ],
  [
    "AI Foundations",
    "OpenAI Academy",
    "Beginner",
    "AI Literacy",
    "Official resource",
    "AI basics, language models, prompting, output review, and responsible everyday use.",
    "https://academy.openai.com/",
  ],
  [
    "Artificial Intelligence Fundamentals",
    "IBM SkillsBuild",
    "Beginner",
    "AI Literacy",
    "Free",
    "Explore machine learning, NLP, computer vision, neural networks, and AI ethics.",
    "https://skillsbuild.org/college-students/course-catalog/artificial-intelligence-fundamentals",
  ],
  [
    "Generative AI Explained",
    "NVIDIA",
    "Beginner",
    "AI Literacy",
    "Free",
    "A no-code overview of generative AI concepts, applications, and challenges.",
    "https://learn.nvidia.com/courses/course-detail?course_id=course-v1%3ADLI+S-FX-07+V1",
  ],
  [
    "AI for Beginners",
    "Microsoft",
    "Beginner / Intermediate",
    "Beginner AI Builder",
    "Open source",
    "A 12-week curriculum with practical lessons, quizzes, labs, and AI ethics.",
    "https://github.com/microsoft/ai-for-beginners",
  ],
  [
    "CS50's AI with Python",
    "Harvard / edX",
    "Intermediate",
    "Beginner AI Builder",
    "Free to audit",
    "A project-based introduction to search, optimization, learning, and neural networks.",
    "https://pll.harvard.edu/course/cs50s-introduction-artificial-intelligence-python",
  ],
  [
    "Machine Learning Crash Course",
    "Google Developers",
    "Beginner / Intermediate",
    "Machine Learning",
    "Free",
    "Videos, interactive visualizations, and exercises for practical ML fundamentals.",
    "https://developers.google.com/machine-learning/crash-course",
  ],
  [
    "Intro to Machine Learning",
    "Kaggle Learn",
    "Beginner",
    "Machine Learning",
    "Free",
    "Build your first models through concise, hands-on lessons in the browser.",
    "https://www.kaggle.com/learn/intro-to-machine-learning",
  ],
  [
    "Intermediate Machine Learning",
    "Kaggle Learn",
    "Beginner / Intermediate",
    "Machine Learning",
    "Free",
    "Handle missing values, categories, data leakage, and model improvement.",
    "https://www.kaggle.com/learn/intermediate-machine-learning",
  ],
  [
    "Practical Deep Learning for Coders",
    "fast.ai",
    "Intermediate",
    "Deep Learning",
    "Free",
    "Apply deep learning to real problems with a practical, code-first course.",
    "https://course.fast.ai/",
  ],
  [
    "LLM Course",
    "Hugging Face",
    "Intermediate",
    "Generative AI & LLMs",
    "Free",
    "Learn Transformers, Datasets, Tokenizers, Accelerate, and the Hugging Face Hub.",
    "https://huggingface.co/learn/llm-course/en/chapter1/1",
  ],
  [
    "Generative AI for Beginners",
    "Microsoft",
    "Beginner / Intermediate",
    "Generative AI & LLMs",
    "Open source",
    "A 21-lesson path for building generative AI applications.",
    "https://github.com/microsoft/generative-ai-for-beginners",
  ],
  [
    "Introduction to Large Language Models",
    "Google Skills",
    "Beginner",
    "Generative AI & LLMs",
    "Free",
    "Understand LLMs, common use cases, prompt tuning, and tools for GenAI apps.",
    "https://www.skills.google/course_templates/539",
  ],
  [
    "Introduction to Responsible AI",
    "Google Skills",
    "Beginner",
    "Responsible AI",
    "Free",
    "A beginner-friendly introduction to responsible AI principles, why they matter, and how teams put them into practice.",
    "https://www.skills.google/course_templates/554",
    {
      labels: ["Beginner", "Ethics", "Fairness", "Google"],
      learn: [
        "What responsible AI means in real products",
        "Why fairness, transparency, privacy, and accountability matter",
        "How to recognize risks before trusting AI outputs",
      ],
      bestFor: "beginners using AI tools for school, research, or early projects.",
    },
  ],
  [
    "Responsible AI Guide",
    "Google Developers",
    "Beginner / Builder",
    "Responsible AI",
    "Official guide",
    "A practical builder guide to responsible AI concepts, shared terms, and implementation practices.",
    "https://developers.google.com/machine-learning/guides/intro-responsible-ai",
    {
      labels: ["Builder", "Ethics", "Privacy", "Fairness"],
      learn: [
        "How to discuss responsible AI risks with shared language",
        "Ways to evaluate models beyond demo performance",
        "How to document limits, fairness concerns, and safer use",
      ],
      bestFor: "students building AI projects who need a responsible design checklist.",
    },
  ],
  [
    "CS229: Machine Learning",
    "Stanford University",
    "Advanced",
    "Machine Learning",
    "Official materials",
    "A broad introduction to supervised learning, unsupervised learning, learning theory, reinforcement learning, and modern applications.",
    "https://cs229.stanford.edu/",
  ],
  [
    "MIT 6.036: Introduction to Machine Learning",
    "MIT Open Learning Library",
    "Intermediate",
    "Machine Learning",
    "Free",
    "A rigorous introduction to modeling, prediction, classification, and machine learning foundations.",
    "https://openlearninglibrary.mit.edu/courses/course-v1%3AMITx%2B6.036%2B1T2019/course/",
  ],
  [
    "AI Agents Course",
    "Hugging Face",
    "Intermediate",
    "Generative AI & LLMs",
    "Free",
    "Build and evaluate AI agents using smolagents, LlamaIndex, LangGraph, tools, and hands-on assignments.",
    "https://huggingface.co/learn/agents-course/en/unit0/introduction",
  ],
  [
    "MIT 6.S191: Introduction to Deep Learning",
    "MIT",
    "Intermediate",
    "Deep Learning",
    "Free and open source",
    "An intensive introduction to neural networks with labs in vision, language, generative modeling, and reinforcement learning.",
    "https://introtodeeplearning.com/",
  ],
  [
    "Full Stack Deep Learning",
    "The Full Stack",
    "Advanced",
    "Deep Learning",
    "Free forever",
    "Learn the complete lifecycle of deep learning systems, from data and experiments to deployment, monitoring, and ethics.",
    "https://fullstackdeeplearning.com/course/2022/",
  ],
  [
    "Interactive Prompt Engineering Tutorial",
    "Anthropic",
    "Beginner / Intermediate",
    "Generative AI & LLMs",
    "Free and open source",
    "A hands-on tutorial for writing, testing, and improving prompts through progressively challenging exercises.",
    "https://github.com/anthropics/prompt-eng-interactive-tutorial",
  ],
  [
    "CS188: Introduction to Artificial Intelligence",
    "UC Berkeley",
    "Intermediate",
    "Beginner AI Builder",
    "Free course materials",
    "Study search, games, decision processes, reinforcement learning, probability, machine learning, logic, LLMs, and AI safety.",
    "https://inst.eecs.berkeley.edu/~cs188/",
  ],
  [
    "Machine Learning Zoomcamp",
    "DataTalks.Club",
    "Intermediate",
    "Machine Learning",
    "Free and open source",
    "A four-month practical course covering ML fundamentals, model deployment, deep learning, serverless systems, and portfolio projects.",
    "https://github.com/DataTalksClub/machine-learning-zoomcamp",
  ],
  [
    "MLOps Course",
    "Made With ML / Anyscale",
    "Advanced",
    "Machine Learning",
    "Free",
    "Design, develop, deploy, test, and continuously improve production machine learning applications.",
    "https://madewithml.com/courses/mlops/",
  ],
  [
    "Learn the Basics with PyTorch",
    "PyTorch",
    "Beginner",
    "Deep Learning",
    "Official resource",
    "A step-by-step path through tensors, datasets, model building, automatic differentiation, optimization, and saving models.",
    "https://docs.pytorch.org/tutorials/beginner/basics/index.html",
  ],
  [
    "Algebra 1",
    "Khan Academy",
    "Beginner",
    "Math Foundations",
    "Free",
    "Build fluency with equations, functions, systems, exponents, quadratics, and the algebra used throughout AI and data science.",
    "https://www.khanacademy.org/math/algebra",
  ],
  [
    "Statistics and Probability",
    "Khan Academy",
    "Beginner / Intermediate",
    "Math Foundations",
    "Free",
    "Learn distributions, probability, sampling, confidence intervals, hypothesis testing, regression, and analysis of variance.",
    "https://www.khanacademy.org/math/statistics-probability",
  ],
  [
    "Single Variable Calculus",
    "MIT OpenCourseWare",
    "Intermediate",
    "Math Foundations",
    "Free open courseware",
    "Study differentiation, integration, applications, and infinite series through lectures, worked examples, problem sets, and exams.",
    "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/",
  ],
  [
    "Linear Algebra",
    "MIT OpenCourseWare",
    "Intermediate",
    "Math Foundations",
    "Free open courseware",
    "Learn matrices, vector spaces, least squares, eigenvalues, and singular value decomposition, the language behind modern machine learning.",
    "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
  ],
  [
    "Probabilistic Systems Analysis and Applied Probability",
    "MIT OpenCourseWare",
    "Intermediate / Advanced",
    "Math Foundations",
    "Free open courseware",
    "Develop a rigorous foundation in probability models, random variables, random processes, laws of large numbers, and inference.",
    "https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/",
  ],
  [
    "Matrix Methods in Data Analysis, Signal Processing, and Machine Learning",
    "MIT OpenCourseWare",
    "Advanced",
    "Math Foundations",
    "Free open courseware",
    "Connect linear algebra to data analysis, optimization, probability, neural networks, deep learning, and modern machine learning algorithms.",
    "https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/",
  ],
  [
    "Matrix Calculus for Machine Learning and Beyond",
    "MIT OpenCourseWare",
    "Advanced",
    "Math Foundations",
    "Free open courseware",
    "Study derivatives of matrix factorizations, constrained optimization, adjoint methods, and automatic differentiation for machine learning.",
    "https://ocw.mit.edu/courses/18-s096-matrix-calculus-for-machine-learning-and-beyond-january-iap-2023/",
  ],
  [
    "Statistics for Applications",
    "MIT OpenCourseWare",
    "Advanced",
    "Math Foundations",
    "Free open courseware",
    "Build rigorous statistical foundations for estimation, hypothesis testing, regression, generalized linear models, and machine learning applications.",
    "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/",
  ],
  [
    "EE364A: Convex Optimization I",
    "Stanford Engineering Everywhere",
    "Advanced",
    "Math Foundations",
    "Free course materials",
    "Learn convex analysis, duality, least squares, quadratic programming, gradient methods, and optimization techniques used throughout machine learning.",
    "https://see.stanford.edu/Course/EE364A",
  ],
  [
    "CS50x: Introduction to Computer Science",
    "Harvard / edX",
    "Beginner",
    "Programming",
    "Free open courseware",
    "Learn computational thinking, C, Python, SQL, HTML, CSS, JavaScript, Flask, algorithms, data structures, and problem solving.",
    "https://cs50.harvard.edu/x/",
  ],
  [
    "Introduction to Computer Science and Programming in Python",
    "MIT OpenCourseWare",
    "Beginner",
    "Programming",
    "Free open courseware",
    "Build confidence writing small Python programs while learning computation, decomposition, abstraction, testing, and algorithms.",
    "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
  ],
  [
    "Python for Everybody",
    "University of Michigan / PY4E",
    "Beginner",
    "Programming",
    "Free",
    "Start Python from zero and progress through variables, functions, loops, files, data structures, web services, databases, and visualization.",
    "https://www.py4e.com/lessons",
  ],
  [
    "Foundations",
    "The Odin Project",
    "Beginner",
    "Programming",
    "Free and open source",
    "A project-based path through web basics, the command line, Git, HTML, CSS, JavaScript, DOM work, and clean coding habits.",
    "https://www.theodinproject.com/paths/foundations/courses/foundations",
  ],
  [
    "JavaScript Algorithms and Data Structures",
    "freeCodeCamp",
    "Beginner / Intermediate",
    "Programming",
    "Free certification",
    "Practice modern JavaScript fundamentals, functions, arrays, objects, classes, functional programming, regular expressions, and algorithmic thinking.",
    "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/",
  ],
  [
    "MDN Curriculum: Core Modules",
    "MDN Web Docs",
    "Beginner / Intermediate",
    "Programming",
    "Free documentation",
    "Learn web standards, semantic HTML, CSS, JavaScript, accessibility, design basics, and version control from MDN's structured curriculum.",
    "https://developer.mozilla.org/en-US/curriculum/core/",
  ],
  [
    "The Missing Semester of Your CS Education",
    "MIT",
    "Intermediate",
    "Programming",
    "Free course materials",
    "Master practical developer tools including the shell, editors, debugging, profiling, version control, packaging, code quality, and modern AI-assisted workflows.",
    "https://missing.csail.mit.edu/",
  ],
].map(([title, provider, level, category, tag, description, url, details = {}]) => ({
  title,
  provider,
  level,
  category,
  tag,
  description,
  url,
  ...details,
}));
export const projects = [
  [
    "AI Study Assistant",
    "Beginner",
    "2-3 weekends",
    "Turn class notes into summaries, flashcards, and review questions.",
    ["Prompting", "APIs", "UI design"],
  ],
  [
    "Resume Keyword Matcher",
    "Beginner",
    "1-2 weekends",
    "Compare a resume with a role and surface missing skills.",
    ["NLP", "Text processing", "Embeddings"],
  ],
  [
    "Image Classifier",
    "Intermediate",
    "3-4 weekends",
    "Train a model to classify images with a friendly dataset.",
    ["Computer vision", "Neural networks"],
  ],
  [
    "Movie Recommender",
    "Intermediate",
    "2-3 weekends",
    "Suggest films from ratings and user preference data.",
    ["Data science", "Recommendations"],
  ],
  [
    "Speech Emotion Classifier",
    "Intermediate",
    "4-5 weekends",
    "Use audio features to classify vocal state and emotion.",
    ["Audio AI", "Feature extraction", "ML"],
  ],
  [
    "Responsible AI Audit",
    "Beginner / Intermediate",
    "1 weekend",
    "Test a system for hallucinations, bias, privacy, and failure cases.",
    ["Evaluation", "Ethics", "Documentation"],
  ],
  [
    "Lightweight Edge AI Demo",
    "Advanced",
    "4-6 weekends",
    "Run a compact model under tight latency and compute limits.",
    ["Optimization", "Latency", "Deployment"],
  ],
].map(([title, level, time, description, skills]) => ({
  title,
  level,
  time,
  description,
  skills,
}));
export const orgs = [...new Set(courses.map((course) => course.provider))];
